services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    MangoSylius\OrderCommentsPlugin\Form\Type\OrderMessageType:
        arguments:
            - '%mango_order_comments_plugin.model.order_message.class%'
        tags:
            - name: form.type

    MangoSylius\OrderCommentsPlugin\Controller\OrderMessageController:
        tags:
            - 'controller.service_arguments'
        arguments:
            $router: '@router'
            $flashBag: '@session.flash_bag'
            $translator: '@translator'
            $mailer: '@sylius.email_sender'
            $twig: '@twig'
            $builder: '@form.factory'
            $tokenStorage: '@security.token_storage'
            $orderRepository: '@sylius.repository.order'
            $orderMessageRepository: '@mango_order_comments_plugin.repository.order_message'
